//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TechFix.manage_quotations {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Manage_QuotationsSoap", Namespace="http://tempuri.org/")]
    public partial class Manage_Quotations : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ApproveQuotationOperationCompleted;
        
        private System.Threading.SendOrPostCallback RejectQuotationOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Manage_Quotations() {
            this.Url = global::TechFix.Properties.Settings.Default.TechFix_manage_quotations_Manage_Quotations;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ApproveQuotationCompletedEventHandler ApproveQuotationCompleted;
        
        /// <remarks/>
        public event RejectQuotationCompletedEventHandler RejectQuotationCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ApproveQuotation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ApproveQuotation(int quotationId, string supplier, string productName, int requiredQuantity, decimal totalPrice) {
            object[] results = this.Invoke("ApproveQuotation", new object[] {
                        quotationId,
                        supplier,
                        productName,
                        requiredQuantity,
                        totalPrice});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ApproveQuotationAsync(int quotationId, string supplier, string productName, int requiredQuantity, decimal totalPrice) {
            this.ApproveQuotationAsync(quotationId, supplier, productName, requiredQuantity, totalPrice, null);
        }
        
        /// <remarks/>
        public void ApproveQuotationAsync(int quotationId, string supplier, string productName, int requiredQuantity, decimal totalPrice, object userState) {
            if ((this.ApproveQuotationOperationCompleted == null)) {
                this.ApproveQuotationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnApproveQuotationOperationCompleted);
            }
            this.InvokeAsync("ApproveQuotation", new object[] {
                        quotationId,
                        supplier,
                        productName,
                        requiredQuantity,
                        totalPrice}, this.ApproveQuotationOperationCompleted, userState);
        }
        
        private void OnApproveQuotationOperationCompleted(object arg) {
            if ((this.ApproveQuotationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ApproveQuotationCompleted(this, new ApproveQuotationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RejectQuotation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RejectQuotation(int quotationId) {
            object[] results = this.Invoke("RejectQuotation", new object[] {
                        quotationId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RejectQuotationAsync(int quotationId) {
            this.RejectQuotationAsync(quotationId, null);
        }
        
        /// <remarks/>
        public void RejectQuotationAsync(int quotationId, object userState) {
            if ((this.RejectQuotationOperationCompleted == null)) {
                this.RejectQuotationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRejectQuotationOperationCompleted);
            }
            this.InvokeAsync("RejectQuotation", new object[] {
                        quotationId}, this.RejectQuotationOperationCompleted, userState);
        }
        
        private void OnRejectQuotationOperationCompleted(object arg) {
            if ((this.RejectQuotationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RejectQuotationCompleted(this, new RejectQuotationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ApproveQuotationCompletedEventHandler(object sender, ApproveQuotationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ApproveQuotationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ApproveQuotationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void RejectQuotationCompletedEventHandler(object sender, RejectQuotationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RejectQuotationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RejectQuotationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591